name: 'Gatorgrade'
description: 'Execute Gatorgrade'
author: 'Katherine Burgess'
runs:
  using:
  steps:
    - run: |
        echo "::group:: Install Pipenv"
        pip install pipenv==2022.4.21
        echo "::endgroup::"
        echo"::add-matcher::${{ github.action_path }}/gatorgrade-problem-matcher.json
        gradle --no-daemon gradle
        echo "::remove-matcher owner=gatorgrade::"
      shell: bash
branding:
  icon: 'user-check'
  color: 'green'
